dist: bionic
language: java
before_install:
  - rm ~/.m2/settings.xml
jdk:
  - openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
    - $HOME/.m2
branches:
  except:
  - /^release\/.*$/
after_success:
  - bash <(curl -s https://codecov.io/bash)
